<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>agree_btn</name>
   <tag></tag>
   <elementGuidId>94b74439-e640-4954-9ec2-82fdf0082109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#agree-btn</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
