<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_popUp</name>
   <tag></tag>
   <elementGuidId>07c13f3e-f3e9-470d-8b1e-e21bfe9f7897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close-popup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='first-visit-popup']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;×&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f9427ba6-55ad-4a94-acc1-ea490fb19edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-popup</value>
      <webElementGuid>77ddd8ef-c368-44fd-98c5-bf27cb5c77d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>19a6fd89-8691-4829-b765-15c24b650e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;first-visit-popup&quot;)/div[@class=&quot;first-popup-content&quot;]/div[1]/span[@class=&quot;close-popup&quot;]</value>
      <webElementGuid>da402b57-8e71-445b-abfb-48411df310a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='first-visit-popup']/div/div/span</value>
      <webElementGuid>150cf4e5-9dc8-4809-aa44-e0e51da534a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return to Site'])[1]/following::span[1]</value>
      <webElementGuid>a74230f3-b856-4cf4-be58-6b137e5a045b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password Assistance'])[2]/following::span[1]</value>
      <webElementGuid>4ac68cd3-c331-4349-bbcd-f3df097e1b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to the new Maverick Label website experience!'])[1]/preceding::span[1]</value>
      <webElementGuid>72184bc6-14b8-4a9f-a21c-8d1df3e18254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CustomerCare@MaverickLabel.Com'])[1]/preceding::span[1]</value>
      <webElementGuid>b7605638-0c69-49ba-b627-65f57901b7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>78914b15-1854-42cc-b2ea-37c316886f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>30a671e4-d8e6-4d38-9155-0742a015f0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>82cd0135-fc50-44d9-ad47-3951253e1b0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
