<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>51f1b589-8d36-449b-b28c-9ef951af446f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quoter-continue-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='quoter-continue-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2cd5653e-7cb6-4415-9669-00d1f1d1ea2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4180e687-0abe-4589-bc87-23cb6cfaa1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quoter-continue-btn</value>
      <webElementGuid>9693108a-705a-4e09-8637-460baf19be72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 col-sm btn btn-primary order-sm-2 ms-sm-2 checkout-btn quoter-buttons mob-ml-0 mob-ml-8</value>
      <webElementGuid>9f106f67-c569-4368-940d-24b8ef8311cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>f2978c36-fd3c-4bc0-b8f0-428461e1c4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quoter-continue-btn&quot;)</value>
      <webElementGuid>aa1abcc4-73a6-4c3b-a4ae-1998d4dc2090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='quoter-continue-btn']</value>
      <webElementGuid>f6047aa3-88a0-4789-bb20-83860a49fc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='quote-form']/div[17]/div/div/button[2]</value>
      <webElementGuid>e6a615cd-3a12-45c3-94c7-145ab2415f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Quote'])[2]/following::button[1]</value>
      <webElementGuid>387f5f7e-b14b-48cb-b3b3-5806683c6f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Step: Upload Artwork'])[1]/following::button[2]</value>
      <webElementGuid>dd1b995f-8132-4680-a9cc-65a3c64c310f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material Information'])[1]/preceding::button[1]</value>
      <webElementGuid>9cca0bac-a7b0-457a-9a2b-5f67cffffbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vinyl – Standard 4 mil – White'])[1]/preceding::button[2]</value>
      <webElementGuid>702767b2-4e58-47cf-bd3f-d690fe27ccbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>389dfcdc-cff6-4ced-a8d7-3497d646f10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/button[2]</value>
      <webElementGuid>09aabfe8-4b8d-43e1-82dc-891505aa223e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'quoter-continue-btn' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>c772f7a4-7d64-4036-82f5-64148c30f016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
