<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Width_custom-width</name>
   <tag></tag>
   <elementGuidId>eac11673-b8cb-439f-9fcf-fadfde967e28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#custom-width-inches</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='custom-width-inches']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#custom-width-inches</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a5b93d5-188b-478b-849b-8be6c7c5096d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>custom-width</value>
      <webElementGuid>f6ee466b-508d-4bcc-be69-1b282d8277a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custom-width-inches</value>
      <webElementGuid>a962e822-80c8-4abf-ac6b-6d8eb5eaf635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.00001</value>
      <webElementGuid>f1998fc1-4753-4258-8aa6-254c1dcaf937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ccbaaba8-c7f8-4308-ac7a-90cb45ebed87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control bg-transparent mob-w-full primary-color</value>
      <webElementGuid>95b08632-3b3c-4082-938e-de54010974a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-width-inches&quot;)</value>
      <webElementGuid>5d482842-d33c-49fe-9b5c-acffd604333b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='custom-width-inches']</value>
      <webElementGuid>34df9cd5-054a-4ec2-9ba6-a92b38e22231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='quote-form']/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>011c51af-1340-4685-863a-311bcf34cfce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>34b9db76-54c1-47f4-a8ca-56c4d4dc1a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'custom-width' and @id = 'custom-width-inches' and @type = 'number']</value>
      <webElementGuid>d21b5b40-7a87-465b-81ec-e2f1eafb54ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
