<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Height_custom-height</name>
   <tag></tag>
   <elementGuidId>9d96d121-9ee5-46ac-88a4-052d45aeed1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#custom-height-inches</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='custom-height-inches']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#custom-height-inches</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1870072-3ab2-425d-9a5d-8fc037efb627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>custom-height</value>
      <webElementGuid>ee8a74ed-bad0-4286-a1d3-a1cc9492cfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custom-height-inches</value>
      <webElementGuid>c7c1416d-d915-48c5-b100-b42dee58f73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.00001</value>
      <webElementGuid>ab070574-e32f-42c7-a44f-ed8cfdc911b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9dbd29ff-5826-4f01-8d67-1477282d4c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control bg-transparent mob-w-full primary-color</value>
      <webElementGuid>b0ac6f3a-630e-490c-a1c8-8f964d21109d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-height-inches&quot;)</value>
      <webElementGuid>9579a157-78ec-4147-b6b7-1bd448132093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='custom-height-inches']</value>
      <webElementGuid>a310d34f-3189-4500-8c31-e182f91cdcc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='quote-form']/div/div/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>1e1c305e-171a-4ae2-b2d1-2fe18ce1c504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>b0e7f635-2471-4526-a2a5-825ebacd0dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'custom-height' and @id = 'custom-height-inches' and @type = 'number']</value>
      <webElementGuid>cb372982-e3c9-45a8-a682-ae7e84c35cd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
