<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_distribution</name>
   <tag></tag>
   <elementGuidId>079a623a-31b8-4336-8e87-61d7ecc858bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.container-pa_label-distribution</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;$5,248.80&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f4bfad6-8de2-4adc-8ffb-a7a007a96676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cbc4ae79-76f6-4516-9e41-755cdc7cb62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preset_quantity</value>
      <webElementGuid>04a713bd-c97c-40a1-a030-8cd02873c8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>750</value>
      <webElementGuid>3ec9888c-ae0d-46f0-8397-8c09f01aa00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>750</value>
      <webElementGuid>d41fa435-1d7e-423b-a4fc-76ba8aea09bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>preset-radio -mt-8 form-check-input sequenceCls number-quote-input cursor-pointer position-absolute selectQuantity-input</value>
      <webElementGuid>bfc97be1-dae9-492c-92ea-93b1a96e6801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>750</value>
      <webElementGuid>69d37e44-ec99-408c-b15e-698c0526f2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;750&quot;)</value>
      <webElementGuid>4740a1a8-80f1-423e-b67e-d2203b4a5477</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='750']</value>
      <webElementGuid>4621e1d6-d986-42da-a443-e00cb065a3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='quote-form']/div[15]/div/div[2]/div/table/tr/td/input</value>
      <webElementGuid>3adacd45-ff0f-4ff9-b6a5-cee6729cf8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>4620b75e-4103-4ef7-8943-90ec41f5f20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'preset_quantity' and @id = '750']</value>
      <webElementGuid>8798b148-9a89-4fe1-9f39-dfebf4295a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
