<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>colorSelection</name>
   <tag></tag>
   <elementGuidId>bd568eb9-7985-4a34-8499-5acca2eb3f66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#colorSelection</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
