<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quantity</name>
   <tag></tag>
   <elementGuidId>a82fd3ae-0cab-448d-82f2-a6c87dfccaf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[value=&quot;8-rolls&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
