<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectGreen</name>
   <tag></tag>
   <elementGuidId>889bd34c-1ba5-4ce5-b3c6-b6bdee068e3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[for=&quot;ink_light-green&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
