<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectMaterial</name>
   <tag></tag>
   <elementGuidId>d842767c-4f0c-4b19-81a3-070a2a394fa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#materialSelection</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
