<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectWhitePaper</name>
   <tag></tag>
   <elementGuidId>9990d9cf-5ac0-469a-b1f7-68016a72180d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[for=&quot;3-material-1&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
